# Generated by Django 3.1.2 on 2020-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201112_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Activated', 'Activated'), ('Cancelled', 'Cancelled'), ('Created', 'Created')], default='Pending', max_length=9),
        ),
    ]
